### ISSUE TITLE
S11: As a player I want to be able to choose on what values (population, directions etc.) the game is played

### ISSUE THREAD

**Issue by LukZeh** [sopra-fs21-group-11/sopra-server#12]
- [ ] when the player opens the game he can choose on what values is played
- [ ] the player should have the possibility to choose between (direction, population, random etc.)
- [ ] It must be possible to play the game along two axes (e.g. north-south and east-west, population and area, …)

**Comment by tanzilkm** [comment]
Not for this milestone
