### ISSUE TITLE
S3b: Story As a player I want to pick two cards to compare after I doubted their placement to prove that my doubt is right.

### ISSUE THREAD

**Issue by theDebbister** [sopra-fs21-group-11/sopra-server#4]
- [ ] the player picks two cards to compare which are revealed (the possible cards are highlighted).
- [ ] If the placement is wrong, the wrongly placed card goes out of the game and the player that placed it wrongly, has to give a token to the doubter
- [ ] If the placement is correct, the doubter has to give a token to the player that placed the card
- [ ] After the doubting evaluation, the two cards and their coordinates are visible for a short amount of

**Comment by tanzilkm** [comment]
-
